name: Build
on: 
  push:
    branches:
      - main
  # Add a new 'workflow_dispatch' trigger to enable Manually Running Job
  workflow_dispatch:
    inputs:
      parameter_name:
        description: Description of the input parameter
        required: true
        default: default_value
jobs:
  macos:
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - os: macos-latest
            target: aarch64-apple-darwin
            use-cross: false
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          swift build -c release --disable-sandbox
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release
          files: .build/release/dark-mode-notify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
